# Generated by Django 5.1.4 on 2024-12-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="phone",
            field=models.CharField(max_length=16, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="category",
            field=models.ManyToManyField(
                to="estoque.categoria", verbose_name="Categoria"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="code",
            field=models.CharField(max_length=30, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data Criação"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="estoque.fornecedor",
                verbose_name="Fornecedor",
            ),
        ),
    ]
