# Generated by Django 5.1.4 on 2024-12-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0002_alter_produto_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
